version: '3.7'

services:
  frontend:
    build: ./frontend
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules/
    networks:
      - frontend

  backend:
    build: ./backend
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - postgres
    networks:
      - frontend
      - backend

  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgres/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wgplaner
    ports:
      - 5432:5432
    networks:
      - backend

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: galkaev
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres:

networks:
  frontend:
  backend:
