image: node:latest

lint-backend:
  stage: lint
  script:
    - cd backend
    - npm install
    - npm run lint
  needs: []

unit-test-backend:
  stage: test
  needs: []
  script:
    - cd backend
    - npm install
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  cache:
    paths:
      - backend/coverage/
  artifacts:
    when: always
    paths:
      - backend/coverage/
    reports:
      junit:
        - backend/junit.xml
      cobertura: backend/coverage/cobertura-coverage.xml

build-backend:
  stage: build
  needs: []
  script:
    - cd backend
    - npm install
    - npm run build

build-documentation:
  stage: build
  needs:
    - unit-test-backend
  dependencies:
    - unit-test-backend
  cache:
    paths:
      - backend/documentation/
  script:
    - cd backend
    - npm install
    - npm run doc
  artifacts:
    paths:
      - backend/documentation/
  only:
    - main

pages:
  stage: deploy
  dependencies:
    - build-documentation
  needs:
    - build-documentation
  script:
    - mkdir public
    - cp -r backend/documentation/* public
  artifacts:
    paths:
      - public
  only:
    - main
