image: node:latest

cache:
  key:
    files:
      - backend/package.json
  paths:
    - backend/node_modules/

before_script:
  - cd backend
  - npm install

lint-backend:
  stage: lint
  script:
    - npm run lint

unit-test-backend:
  stage: test
  script:
    - npm run test:ci
  cache:
    paths:
      - backend/coverage/
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    when: always
    reports:
      junit:
        - backend/junit.xml
      cobertura: backend/coverage/cobertura-coverage.xml

integration-test-backend:
  stage: test
  script:
    - npm run test:e2e

pages:
  stage: deploy
  dependencies:
    - unit-test-backend
  script:
    - mkdir .public
    - cp -r backend/coverage/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main
